name: GSI Build

on: [push]

env:
  ROM_URL: https://doc-14-8k-docs.googleusercontent.com/docs/securesc/s12be63h46emjeudohlg8spg3tle1l6g/r79eh8m7cj54kktkflov6stnsj7ol4s4/1603320000000/01187829675333775993/10538182007965579340/1SFJVU6r_9eyf1rW0cxyO_0pvd0c25MGR?e=download&authuser=0&nonce=tvut5ifmfpcn4&user=10538182007965579340&hash=kmrep859um1snvege31ll5moqqkecj5a
  ZIP_NAME: hentaiOS
  TG_NAME: "hentaiOS Rika"
  ROM_NAME: Pixel
  TZ: America/Edmonton
  MIR: wet
  NOTES: "#hentaiOS #crosshatch"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Porting GSI
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename A-only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Sending build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/robot.py
