name: GSI Build

on: [push]

env:
  ROM_URL: https://mirrorbits.lineageos.org/full/I01WD/20200925/lineage-17.1-20200925-nightly-I01WD-signed.zip
  ROM_NAME: Generic
  ZIP_NAME: Lineage
  TZ: Europe/London
  NOTES: "#Stable #BotTest #Android10"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --depth=1 --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Porting GSI
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename A-only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Sending build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/robot.py
